# Generated by Django 5.1 on 2024-09-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=25)),
                ('year', models.IntegerField()),
                ('color', models.CharField(max_length=25)),
                ('photo', models.ImageField(upload_to='app/images/')),
            ],
        ),
    ]
